#!/bin/csh
nkf -m Ref_man_jp.rd | rd2 --out-code=utf-8 | \
      sed -e 's/<dt>/<dt><h4>/' -e 's/<\/dt>/<\/h4><\/dt>/' \
      > Ref_man_jp.html
rd2 Ref_man.rd  | \
      sed -e 's/<dt>/<dt><h4>/' -e 's/<\/dt>/<\/h4><\/dt>/' \
      > Ref_man.html
